const prompt = require('prompt-sync')({sigint:true});

// Variables

let time = 6
let totalPokemon = 0


// Empty Arrays

let caughtPokemon = [];
// let caughtPokemonWeight = [];
// let caughtPokemonValue = [];

// Descriptive Arrays

const adj1 = ["bold", "timid", "calm", "bashful", "quirky", "sassy", "brave", "gentle", "docile", "jolly"];
const adj2 = ["alpha", "baby", "mega", "noble", "old", "gigantamax", "tiny", "rare", "shiny", "common"];
const waterPokemon = ["Magikarp", "Tentacool", "Krabby", "Dratini", "Squirtle", "Horsea", "Staryu", "Feebas", "Slowpoke", "Shellder"];

// Functions

function randomPokemonGenerator() {

    let randomAdj1 = adj1[Math.floor(Math.random() * adj1.length)];
    let randomAdj2 = adj2[Math.floor(Math.random() * adj2.length)];
    let randomWaterPokemon = waterPokemon[Math.floor(Math.random() * waterPokemon.length)];

    return `${randomAdj1} ${randomAdj2} ${randomWaterPokemon}`;
    
}
// max weight 5lbs (not including max) so you're not done at one fish
function randomWeightGenerator(min, max) {

    let weight = (Math.random() * (5.00 - 1.00) + 1.00).toFixed(2);
    
    return weight;
    
}
// max value $100 (including max) 
function randomValueGenerator(min, max) {

    let value = (Math.random() * (100.00 - 1.00 + 1.00) + 1.00).toFixed(2);

    return value;
    
}

function totalWeightGenerator() {
    let sum = 0

    for (let count = 0; count < caughtPokemon.length; count++) {
        
        sum = sum + Number(caughtPokemon[count].weight);
        
    }
   return sum.toFixed(2);

    
}

function totalValueGenerator() {
    let sum = 0

    for (let count = 0; count < caughtPokemon.length; count++) {

        sum = sum + Number(caughtPokemon[count].value);
        
    }
    return sum.toFixed(2);
    
}

// Variables generated by functions

let randomPokemon = randomPokemonGenerator();
let randomWeight = randomWeightGenerator();
let randomValue = randomValueGenerator();
let totaledWeight = totalWeightGenerator();
let totaledValue = totalValueGenerator();

// Start up dialogue
console.log("*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*");

console.log ("*~Welcome to the Safari Zone!~*")

console.log("...");

console.log ("Congrats! You recieved a 'Great Rod'!")

console.log("...");

console.log("Let's go fishing for water Pokemon!");

console.log("...");

console.log("Try to maximize the value of your caught pokemon.");

console.log("...");

console.log("You can fish for six hours (till 12:00pm).");

console.log("...");

console.log("10lbs is the max weight you can catch!");

console.log("...");

console.log("Good Luck!");

console.log("...");
console.log("\n")

// one hour for each fish, so the time can increment by one with the fish in the loop.

while (time <= 11) {

    
    

    randomPokemon = randomPokemonGenerator();
    randomWeight = randomWeightGenerator();
    randomValue = randomValueGenerator();
    totaledWeight = totalWeightGenerator();
    totaledValue = totalValueGenerator();

    const pokemonObject = {
        pokemon: randomPokemon,
        weight: randomWeight,
        value: randomValue
    }


    console.log("*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*");
    console.log("\n")
    console.log("The time is "+ time +":00am. So far, your catch totals are:")
    console.log(+ totalPokemon + ` pokemon, ${totaledWeight} lbs, $${totaledValue}`);
    console.log("...");
    console.log(`You encountered a ${randomPokemon} weighing ${randomWeight} lbs with a value of $${randomValue}!`);
    console.log("...");

    if (Number(totaledWeight) + Number(randomWeight) > 10) {
        
        console.log("You've exceeded the maximum weight limit, you must select [r]un!");
        console.log("\n")

    } else if ( Number(totaledWeight) + Number(randomWeight) <= 10 ) {

        console.log("Your action: [c]atch or [r]un?")
        console.log("\n")
        
        
    }

    let selection = prompt("> ");
    
    if (selection.toLowerCase() === 'c' && Number(totaledWeight) + Number(randomWeight) <= 10) {
    
        caughtPokemon.push(pokemonObject);
        // caughtPokemonWeight.push(pokemonObject.weight);
        // caughtPokemonValue.push(pokemonObject.value);
        // console.log(caughtPokemon);
        // console.log(caughtPokemonWeight);
        // console.log(caughtPokemonValue);
        totalPokemon++;
        // totaledWeight = totalWeightGenerator();
        // totaledValue = totalValueGenerator();

    } else if (selection.toLowerCase() === 'r') {

        console.log("You ran away!")
        console.log("\n")
        
    } else {
        
        console.log("Invalid input, the pokemon ran away!");
        console.log("\n")
    }
    time ++;
    totaledWeight = totalWeightGenerator();
    totaledValue = totalValueGenerator();
    console.log("Your new catch totals are:")
    console.log(+ totalPokemon + ` pokemon, ${totaledWeight} lbs, $${totaledValue}`);
    if (time === 12) {
        // console.log("The time is now 12:00pm. Times up!");
        // console.log("\n")
        // console.log(caughtPokemon);
        // console.log("\n")
        // console.log("You caught " + totalPokemon + " pokemon!")
        // console.log("\n")
        // console.log("Total Value: $ " + totaledValue + "");
        // console.log("\n")
        // console.log("Total Weight: " + totaledWeight + "lbs");
        // console.log("\n")
        console.log("*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*");
        console.log("The time is now 12:00pm. Times up!");
    }

    
}
console.log("*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*");
// console.log("The time is now 12:00pm. Times up!");
console.log("...");
console.log("You caught " + totalPokemon + " pokemon:")
for (let count = 0; count < caughtPokemon.length; count++) {
    console.log("* " + caughtPokemon[count].pokemon + " , " + caughtPokemon[count].weight + " lbs, $" + caughtPokemon[count].value + "");
    
}
// console.log(caughtPokemon);

console.log("\n")
console.log(`Total Weight: ${totaledWeight} lbs`); 
console.log("\n")
console.log(`Total Value: $${totaledValue}`);
console.log("\n")
console.log("Thank you for playing! Goodbye!")
console.log("*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*");







